name: temporal-models
channels:
  - pytorch
  - huggingface
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - accelerate=0.23.0
  - datasets=2.14.5
  - evaluate=0.4.0
  - pytest=7.4.2
  - python=3.11.5
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - tokenizers=0.13.3
  - transformers=4.33.2
