name: temporal_bert_models
channels:
  - pytorch
  - huggingface
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cuda=11.7.1
  - cuda-toolkit=11.7.1
  - datasets=2.8.0
  - jupyter=1.0.0
  - numpy=1.24.1
  - pip=22.3.1
  - pytest=
  - python=3.8.15
  - pytorch=1.13.1=py3.8_cuda11.7*
  - pytorch-cuda=11.7
  - tokenizers=0.13.0.dev0
  - transformers=4.26.0
